CREATE DATABASE USER_MANAGEMENT;

USE USER_MANAGEMENT;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    mobile VARCHAR(10) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    createdBy VARCHAR(255),
    updatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
    updatedBy VARCHAR(255)
);